### ISSUE TITLE
Antenna Switch

### ISSUE THREAD

**Issue by derekmulcahy** [fdufnews/SMART-Response-XE-schematics#2]
Thanks for the schematics!

My SMART Response XE has the same [Antenna Switch](https://www.mouser.com/datasheet/2/286/upg2214tb-47726.pdf) that you list in the data-sheets.

I wondered how this switch is used. Do you think the original software switches between the two antennas to see which one has the best signal? Or maybe transmit on one and then the other just to be sure to get the best possible range regardless of orientation.

DIG1 and DIG2 select the antenna, with one being high and the other low for each antenna. Not sure why it does just use one signal but it doesn't!

Derek

**Comment by fdufnews** [comment]
I have the same circuit on mine as you can see on the datasheet  directory. The circuit was missing in the Kicad component list and I used an equivalent one. I just forget to update the reference on the schematic.
The antennas are perpendicular one to the other so the software is probably switching between the two antennas to find the best signal. https://www.prowesswireless.com/post/2017/08/19/wifi-antenna-diversity

**Comment by derekmulcahy** [comment]
Thanks, I updated my comment when I saw the Datasheets directory. Thanks for the link.

**Comment by fdufnews** [comment]
Corrected reference of U1 in schematic

**Comment by hotkeymuc** [comment]
In my empirical tests simply activating Antenna Diversity (as described in the ATmega128RFA1 data sheet) significantly increases the RF range on my SMART Response XEs. So it seems to be wired up correctly from the factory :-)

Activate/configure Antenna Diversity before sending by setting
`ANT_DIV = (1<<ANT_DIV_EN) | (1<<ANT_EXT_SW_EN) | (1);`
where ANT_DIV = Register 0x14D, ANT_DIV_EN = 3, ANT_EXT_SW_EN = 2 and the "1" meaning "DIG1=HIGH / DIG2=LOW".

Don't forget to disable it when going to sleep in order to conserve power.

**Comment by derekmulcahy** [comment]
@hotkeymuc thanks for that. I hadn't noticed it in the documentation and I didn't know what to search for. RTFM rules OK!
